### PR TITLE
bt-385: bug fix animation on dropdown selector

### LINKED ISSUE #385: [BUG] Fix animation on dropdown selector
**Description:**
Fix the disappearance of border and jumpy behavior.

**Environment:**
Android 12, Realme 8

**Steps to reproduce:**
1. Open any dropdown
2. Close this dropdown

**Actual Result:**
1. Animation has little lag at the beginning. On close border disappears instantly.
2. Animation on close has jumpy behavior.
3. Current location has no animation.

**Expected Result:**
1. Animation is smooth. On close border disappears progressively.
2. Animation on close should be smooth.
3. Current location should have the same animation as other dropdowns.

**Visual Proof (screenshots, videos, text):**
https://user-images.githubusercontent.com/8355821/267243769-0c56d9c4-8829-4cbb-9d59-354df75c23a2.mp4
https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/8355821/9833ab47-1c83-4421-ace9-85fd36658b5d

**Severity:**
Minor

### PR DESCRIPTION
**Pull request by mskmee**
https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/85788646/4d3bbebb-1d37-4fae-ad64-2850a138345c

https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/85788646/44988354-3990-4091-b8e1-e1d83bfa65f3

### CODE REVIEW

File: mobile/src/bundles/common/hooks/use-selector-height-animation/use-selector-height-animation.ts [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+    return useAnimatedStyle(() => {
+        return {
+            maxHeight: withTiming(
+                isVisible ? MAX_DROPDOWN_HEIGHT : INITIAL_DROPDOWN_HEIGHT,
+                { duration: 400 },
+            ),
+            borderWidth: withTiming(+isVisible, { duration: 400 }),
+        };
+    });
+};
```
Comment (katerynakostikova) [inline mobile/src/bundles/common/hooks/use-selector-height-animation/use-selector-height-animation.ts]: let's combine this 2 hooks in one (useSelectorAnumations)

File: mobile/src/bundles/common/hooks/use-selector-animations/use-selector-animations.ts [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+
+type useSelectorAnimationsReturn = {
+    iconAnimatedStyle: Record<string, unknown>;
+    heightAnimatedStyle: Record<string, unknown>;
+};
+const useSelectorAnimations = (
+    isVisible: boolean,
+): useSelectorAnimationsReturn => {
+    const INITIAL_DROPDOWN_HEIGHT = 0;
+    const MAX_DROPDOWN_HEIGHT = 150;
```
Comment (katerynakostikova) [inline mobile/src/bundles/common/hooks/use-selector-animations/use-selector-animations.ts]: can be moved out of hook

**Review by katerynakostikova — APPROVED** [review]

**Review by illia-dobro — APPROVED** [review]

**Review by nikita-remeslov — APPROVED** [review]
