### PR TITLE
bt-245: Connect onboarding steps wit backend

### LINKED ISSUE #245: Connect onboarding steps with backend
Currently, we don't send any step data to the backend. We need to connect all finished steps with created endpoint

### LINKED ISSUE #384: [BUG] The chosen country does not display in the field "Current location"
**Description:**
[Mobile]: The chosen country does not display in the field "Current location"

**Preconditions:**

**Environment:**
OS - Android 12
App build 13/09/2023 3:40PM

**Steps to reproduce:**

1. Open the app
2. Sign Up with valid data, press “Sign Up”
3. Fill in the required fields on the page “Step 01/05”
4. Choose country in the field "Current location"
5. Pay attention that chosen country does not display in the field "Current location"
6. Press button “Next”
7. Pay attention that validation error about empty field "Current location" does not appears, user is redirected to the next step

**Actual Result:**
The chosen country does not displayed in the field "Current location". The validation error about empty field "Current location" does not appears, user is redirected to the next step

**Expected Result:**
The chosen country displayed in the field "Current location"

**Visual Proof (screenshots, videos, text):**
https://user-images.githubusercontent.com/8355821/267261072-466b16ad-d80f-4e20-9b8a-5cb2b026ccbb.mp4
https://drive.google.com/file/d/11rvz9DF9wX5Y-QuWzNB2VN3I-yXTlWtd/view?usp=drivesdk

**Severity:**
Medium

### LINKED ISSUE #388: [BUG] The next button doesn't work on the Step 03
**Description:**
When the user clicks on the "Next" button he isn't redirected to the next onboarding step

**Preconditions:**
The BSA talent app is open

**Environment:**
Android 13
Samsung Galaxy A52 (2340x1080)

**Steps to reproduce:**
1. Enter a valid email and password
2. Click on Sign up
3. Go to step 3
4. Click on the "Next" button

**Actual Result:**
When the user clicks on the "Next" button he isn't redirected to the next onboarding step

**Expected Result:**
When the user clicks on the "Next" button he is redirected to the next onboarding step

**Visual Proof (screenshots, videos, text):**

**Severity:**
Major (S3)
https://drive.google.com/file/d/123qmj_1pq9v39Z3YMcOFyg6g1klGVsI1/view?usp=drivesdk

### LINKED ISSUE #417: [BUG] Onboarding steps handles phone navigation buttons not right
**Description:**
When user presses the Back navigation button on phone from Step 4(for example) it leads to Step 1.

**Environment:**
Android 12

**Steps to reproduce:**
1. Login to the app
2. Go to Step 4
3. Press Back navigation button on the phone

**Actual Result:**
App returned to Step 1

**Expected Result:**
App returned to the previous step

**Visual Proof (screenshots, videos, text):**
https://user-images.githubusercontent.com/8355821/267709416-7505d81c-0d05-4b11-b6c6-d7751a27e464.mp4

**Severity:**
Medium

### LINKED ISSUE #420: [BUG] The button “Back” doesn’t redirect to the previous page on the page “Step 03/05”
**Description:**
[Mobile]: The button “Back” doesn’t redirect to the previous page on the page “Step 03/05”

**Preconditions:**
The user is on the page “Step 03/05”

**Environment:**
OS - Android
Version - 12 SP1A.210812.016

**Severity**
Critical (S2)

**Steps to reproduce:**

1. Press “Back” on the page “Step 03/05”
2. Pay attention that the user stays on the page “Step 03/05”
3. Press the phone navigation button “Back”
4. Pay attention that the user is redirected to the page “Step 01/05”

**Actual Result:**
The button “Back” doesn’t redirect to the previous page on the page “Step 03/05”. After using the phone navigation button “Back” the user is redirected to the page “Step 01/05” (the same situation on page “Step 04/05”.

**Expected Result:**
The button “Back” on the page “Step 03/05” redirects to the previous page “Step 02/05”

**Visual Proof (screenshots, videos, text):**
https://drive.google.com/file/d/12TQDhmj7xpraQaYStZRMk0CSJ7Mewi1i/view?usp=sharing

### LINKED ISSUE #430: [BUG] Wrong color of placeholder for the "Job title" field
**Description:**
Wrong color of placeholder for the "Job title" field on Step 01

**Preconditions:**
The BSA talent app is open

**Environment:**
Android 13
Samsung Galaxy A52 (2340x1080)

**Steps to reproduce:**
1. Enter a valid email and password
2. Click on Sign up
3. Pay attention to the "Job title" field

**Actual Result:**
The color of the placeholder for the "Job title" field different from other fields

**Expected Result:**
The "Job title" field has a placeholder like other fields (like the "Current location" field)

**Visual Proof (screenshots, videos, text):**
image

**Severity:**
Low

### PR DESCRIPTION
**Pull request by anogire**
Start
Screenshot 2023-09-08 at 22 55 04
Post - after creating
Screenshot 2023-09-08 at 22 59 51
Patch - after updating
Screenshot 2023-09-08 at 23 04 07

But if there are errors when executing a database query, they appear in this form:
Screenshot 2023-09-09 at 00 18 42

### CODE REVIEW

File: mobile/src/bundles/talent/store/actions.ts [hunk 1]
```diff
@@ -1,17 +1,46 @@
...
+        return await talentApi.completeOnboardingStep(stepPayload);
+    } catch (error) {
+        const errorMessage = getErrorMessage(error);
+        notifications.showError({ title: errorMessage });
+        throw error;
+    }
+});
+
+const setCompletedStep = createAction<number>(`${sliceName}/setCompletedStep`);
+
```
Comment (anogire) [inline mobile/src/bundles/talent/store/actions.ts:73]: This completedStep will be created differently in the database

**Comment by anogire** [comment]
Currently, there is no GET request to user-details, so the initial data is always null. And if you execute STEP1 again, a POST request will be sent and an error will occur. Therefore, you need to delete the database record before each session.

File: mobile/src/bundles/talent/store/slice.ts [hunk 2]
```diff
@@ -2,52 +2,63 @@ import { createSlice } from '@reduxjs/toolkit';
...
+    setCompletedStep,
+    updateOnboardingData,
+} from './actions';
 
 type State = {
     dataStatus: ValueOf<typeof DataStatus>;
-    profileStepData: ProfileStepDto | null;
+    onboardingData: UserDetailsResponseDto | null;
+    completedStep: number;
 };
```
Comment (anogire) [inline mobile/src/bundles/talent/store/slice.ts:16]: I wanted to make a state 
```
dataStatus: ValueOf<typeof DataStatus>;
completedStep: number;
profileStepData: ProfileStepDto | null;
cvAndContactsStepData: CVAndContactsStepDto | null;
...
```
But I couldn't :(

Since POST and PATCH requests always return a complete object with all user-details fields, I left only onboardingData. And in each step, we need to get data according to its type. I don't know if it's okay.

**Comment by anogire** [comment]
getTalentsDetails - will work after completion on the backend.
But I still need the **completedStep** field to know whether to create data or update it. Or change the code without it at all.

Screenshot 2023-09-11 at 00 49 18
Screenshot 2023-09-11 at 00 49 28

File: mobile/src/bundles/auth/store/slice.ts [hunk 3]
```diff
@@ -1,29 +1,26 @@
...
+type UserData = UserFindResponseDto & {
     isProfileComplete: boolean;
 };
 // TODO: Replace user data with shared UserData Type
 
 type State = {
     dataStatus: ValueOf<typeof DataStatus>;
     isSignedIn: boolean;
-    userData: UserData | null;
+    currentUser: UserData | null;
```
Comment (katerynakostikova) [inline mobile/src/bundles/auth/store/slice.ts]:
```suggestion
    currentUserData: UserData | null;
```

File: mobile/src/bundles/common/components/selector/selector.tsx [hunk 4]
```diff
@@ -39,6 +39,8 @@ const Selector = <T extends FieldValues>({
     const { value, onChange } = field;
     const [isListVisible, setIsListVisible] = useState(false);
 
+    const placeHolderStyle = value ? {} : styles.placeholder;
```
Comment (katerynakostikova) [inline mobile/src/bundles/common/components/selector/selector.tsx]:
```suggestion
    const placeHolderStyle = value ?? styles.placeholder;
```

File: mobile/src/bundles/auth/store/slice.ts [hunk 5]
```diff
@@ -36,21 +33,26 @@ const { reducer, actions, name } = createSlice({
             (state, { payload }) => {
                 const { email, id, role } = payload;
                 state.dataStatus = DataStatus.FULFILLED;
-                state.userData = { email, role, id, isProfileComplete: false };
+                state.currentUser = {
+                    email,
+                    role,
+                    id,
+                    isProfileComplete: false,
```
Comment (katerynakostikova) [inline mobile/src/bundles/auth/store/slice.ts]: don't we have last completed step in this data?

File: mobile/src/bundles/talent/screens/profile.tsx [hunk 6]
```diff
@@ -1,44 +1,129 @@
...
-        (payload: ProfileStepDto): void => {
-            void dispatch(talentActions.completeProfileStep(payload));
+    const { navigate } =
+        useNavigation<
+            NavigationProp<TalentOnboardingNavigationParameterList>
+        >();
+
+    useEffect(() => {
+        const payload: UserDetailsFindRequestDto = {
+            userId: currentUser?.id ?? '',
```
Comment (katerynakostikova) [inline mobile/src/bundles/talent/screens/profile.tsx]: let's move user id from function, you use it in multiple places

File: mobile/src/bundles/talent/store/slice.ts [hunk 7]
```diff
@@ -2,52 +2,63 @@ import { createSlice } from '@reduxjs/toolkit';
...
+            state.completedStep = action.payload;
         });
+        builder.addMatcher(
+            (action) =>
+                action.type === createTalentDetails.fulfilled.type ||
+                action.type === updateOnboardingData.fulfilled.type ||
+                action.type === getTalentDetails.fulfilled.type,
+            (state, action) => {
+                state.dataStatus = DataStatus.FULFILLED;
+                state.onboardingData = action.payload;
```
Comment (katerynakostikova) [inline mobile/src/bundles/talent/store/slice.ts]: Do all these actions return data related to all steps? If yes, then okay, if only patched data, then you should write like this: state.onboardingData = {...state.onboardingData, ...action.payload};

File: mobile/src/bundles/talent/store/slice.ts [hunk 8]
```diff
@@ -2,52 +2,63 @@ import { createSlice } from '@reduxjs/toolkit';
...
+            },
+        );
+        builder.addMatcher(
+            (action) =>
+                action.type === createTalentDetails.pending.type ||
+                action.type === updateOnboardingData.pending.type ||
+                action.type === getTalentDetails.pending.type,
```
Comment (katerynakostikova) [inline mobile/src/bundles/talent/store/slice.ts]: Action type is different for all statuses (pending, rejected and fulfilled) ?

File: mobile/src/bundles/auth/store/slice.ts (hunk 5 above)
Comment (anogire) [reply mobile/src/bundles/auth/store/slice.ts]: There will be a **completedStep** field in user-details that will contain the name of the last completed step, or null. 
The name is taken from shared/enum
So, I think I can remove isProfileComplete from here completely. And in the [root navigation](mobile/src/navigations/root/root.tsx), request completedStep through the getTalentDetails action.

File: mobile/src/bundles/talent/store/slice.ts (hunk 7 above)
Comment (anogire) [reply mobile/src/bundles/talent/store/slice.ts]: According to Swagger - yes, all queries are expected to return the full object with user-details.

File: mobile/src/bundles/talent/store/slice.ts (hunk 8 above)
Comment (anogire) [reply mobile/src/bundles/talent/store/slice.ts]: fix

**Comment by anogire** [comment]
Screenshot 2023-09-12 at 15 23 10

**Comment by anogire** [comment]
STEP3
Screenshot 2023-09-13 at 13 42 35
Screenshot 2023-09-13 at 13 43 41Screenshot 2023-09-13 at 13 44 02

STEP4
Screenshot 2023-09-13 at 13 44 15Screenshot 2023-09-13 at 13 44 19
Screenshot 2023-09-13 at 13 45 09Screenshot 2023-09-13 at 13 45 17

RESULT in DB
Screenshot 2023-09-13 at 13 46 35
Screenshot 2023-09-13 at 13 47 00

File: mobile/src/bundles/auth/store/slice.ts [hunk 9]
```diff
@@ -40,7 +32,11 @@ const { reducer, actions, name } = createSlice({
             (state, { payload }) => {
                 const { email, id, role } = payload;
                 state.dataStatus = DataStatus.FULFILLED;
-                state.userData = { email, role, id, isProfileComplete: false };
+                state.currentUserData = {
+                    email,
+                    role,
+                    id,
+                };
```
Comment (katerynakostikova) [inline mobile/src/bundles/auth/store/slice.ts:39]: we get only this data in payload?

File: mobile/src/bundles/talent/components/back-form-button/back-form-button.tsx [hunk 10]
```diff
@@ -0,0 +1,43 @@
...
+const BackFormButton: React.FC<Properties> = ({ currentStep }) => {
+    const { navigate } =
+        useNavigation<
+            NavigationProp<TalentOnboardingNavigationParameterList>
+        >();
+
+    const handlePreviousPress = useCallback((): void => {
+        const previousScreenName = getPreviousStepTitle(currentStep);
+        if (previousScreenName) {
+            navigate(previousScreenName, {
```
Comment (katerynakostikova) [inline mobile/src/bundles/talent/components/back-form-button/back-form-button.tsx]:
```suggestion
            replace(previousScreenName, {
```
We don't want user to visit next step on back press

File: mobile/src/bundles/talent/components/cv-and-contacts-form/cv-and-contacts-form.tsx [hunk 11]
```diff
@@ -13,18 +13,26 @@ import { TextCategory } from '~/bundles/common/enums/enums';
 import { useAppForm, useCallback } from '~/bundles/common/hooks/hooks';
 import { globalStyles } from '~/bundles/common/styles/styles';
 import { AvatarPicker } from '~/bundles/talent/components/avatar-picker/avatar-picker';
+import { BackFormButton } from '~/bundles/talent/components/components';
```
Comment (katerynakostikova) [inline mobile/src/bundles/talent/components/cv-and-contacts-form/cv-and-contacts-form.tsx]:
```suggestion
import { OnboardingBackButton } from '~/bundles/talent/components/components';
```

File: mobile/src/bundles/talent/helpers/manage-navigation-steps.ts [hunk 12]
```diff
@@ -0,0 +1,35 @@
...
+} from '~/bundles/common/enums/enums';
+import { type ValueOf } from '~/bundles/common/types/types';
+
+type ScreenName = ValueOf<typeof TalentOnboardingScreenName>;
+
+const STEP = 1;
+
+const screenNames = Object.keys(
+    TalentOnboardingScreenNumber,
+) as (keyof typeof TalentOnboardingScreenName)[];
```
Comment (katerynakostikova) [inline mobile/src/bundles/talent/helpers/manage-navigation-steps.ts]:
```suggestion
) as ScreenName[];
```

File: mobile/src/bundles/talent/helpers/manage-projects-links.ts [hunk 13]
```diff
@@ -0,0 +1,11 @@
+type UrlObject = { url: string };
+
+const stringsToUrlObjects = (links: string[] | null): UrlObject[] => {
+    return links?.map((url) => ({ url })) ?? [];
+};
+
+const urlObjectsToStrings = (links: UrlObject[] | null): string[] => {
+    return links?.map(({ url }) => url) ?? [];
+};
```
Comment (katerynakostikova) [inline mobile/src/bundles/talent/helpers/manage-projects-links.ts:9]: why do we need this?

File: mobile/src/bundles/talent/screens/bsa-badges.tsx [hunk 14]
```diff
@@ -0,0 +1,94 @@
...
+    TalentOnboardingStepState,
+} from '~/bundles/common/enums/enums';
+import {
+    useAppDispatch,
+    useAppRoute,
+    useAppSelector,
+    useCallback,
+    useNavigation,
+} from '~/bundles/common/hooks/hooks';
+import { globalStyles } from '~/bundles/common/styles/global-styles';
```
Comment (katerynakostikova) [inline mobile/src/bundles/talent/screens/bsa-badges.tsx]:
```suggestion
import { globalStyles } from '~/bundles/common/styles/styles';
```

File: mobile/src/bundles/talent/screens/bsa-badges.tsx [hunk 15]
```diff
@@ -0,0 +1,94 @@
...
+            };
+
+            const result = await dispatch(
+                talentActions.updateOnboardingData(updatedBadgesPayload),
+            );
+
+            if (result.payload) {
+                const setStepResult = dispatch(
+                    talentActions.setCompletedStep(stepTitle),
+                );
```
Comment (katerynakostikova) [inline mobile/src/bundles/talent/screens/bsa-badges.tsx]: will we get this completedStep value from the backend in the future?

File: mobile/src/bundles/talent/store/actions.ts [hunk 16]
```diff
@@ -1,33 +1,79 @@
...
+    }
+    try {
+        const response = await talentApi.completeOnboardingStep(payload);
+
+        return {
+            ...response,
+            ...(hardSkills && { hardSkills }),
+            ...(badges && { badges }),
+            ...(photo && { photo }),
+            ...(cv && { cv }),
```
Comment (katerynakostikova) [inline mobile/src/bundles/talent/store/actions.ts:50]: todo remove comment as I remember

File: mobile/src/bundles/talent/store/slice.ts (hunk 2 above)
Comment (katerynakostikova) [reply mobile/src/bundles/talent/store/slice.ts:16]: It's ok

File: mobile/src/bundles/auth/store/slice.ts (hunk 9 above)
Comment (anogire) [reply mobile/src/bundles/auth/store/slice.ts:39]: yes: id, email, role, token

File: mobile/src/bundles/talent/helpers/manage-projects-links.ts (hunk 13 above)
Comment (anogire) [reply mobile/src/bundles/talent/helpers/manage-projects-links.ts:9]: because frontend links should be processed as [{url: ''}, {url: ''}, ...]
But in the database they are stored with the type string[]. That's why we at daily talked about converting them to one or the other way.

File: mobile/src/bundles/talent/screens/bsa-badges.tsx (hunk 15 above)
Comment (anogire) [reply mobile/src/bundles/talent/screens/bsa-badges.tsx]: yes, we discussed that there will be a field in user-details with the name of the last completed step. 
For now i made it only in state, maybe for navigation.

Comment (anogire) [reply mobile/src/bundles/talent/screens/bsa-badges.tsx]: Not number of step, but title

File: mobile/src/bundles/talent/components/back-form-button/back-form-button.tsx (hunk 10 above)
Comment (anogire) [reply mobile/src/bundles/talent/components/back-form-button/back-form-button.tsx]: fixed

File: mobile/src/bundles/common/components/autocomplete-selectors/autocomplete-multi-selector.tsx [hunk 17]
```diff
@@ -99,9 +106,9 @@ const AutocompleteMultiSelector = <T extends FieldValues>({
                         ]}
                     >
                         <ScrollView nestedScrollEnabled>
-                            {filteredItems.map((item: string) => (
+                            {filteredItems.map((item: Options) => (
```
Comment (mskmee) [inline mobile/src/bundles/common/components/autocomplete-selectors/autocomplete-multi-selector.tsx]: Maybe it's better to use destructurisation on item ?

File: mobile/src/bundles/common/components/autocomplete-selectors/autocomplete-multi-selector.tsx [hunk 18]
```diff
@@ -125,10 +132,10 @@ const AutocompleteMultiSelector = <T extends FieldValues>({
                     styles.tagContainer,
                 ]}
             >
-                {value.map((item: string) => (
+                {value.map((item: Options) => (
```
Comment (mskmee) [inline mobile/src/bundles/common/components/autocomplete-selectors/autocomplete-multi-selector.tsx:138]: Same here

**Comment by nikita-remeslov** [comment]
Conflicts

File: mobile/src/bundles/talent/components/skills-and-projects-form/skills-and-projects-form.tsx [hunk 19]
```diff
@@ -145,44 +134,47 @@ const SkillsAndProjectsForm: React.FC<Properties> = ({
                                 <Input
                                     control={control}
                                     name={`projectLinks.${index}.url`}
-                                    placeholder="link to your project"
+                                    placeholder={
+                                        index === 0
```
Comment (mskmee) [inline mobile/src/bundles/talent/components/skills-and-projects-form/skills-and-projects-form.tsx:137]: you can simplify it with
 ```
index ? 'link to BSA project'  : 'link to your project'
```

File: mobile/src/bundles/talent/components/skills-and-projects-form/skills-and-projects-form.tsx [hunk 20]
```diff
@@ -145,44 +134,47 @@ const SkillsAndProjectsForm: React.FC<Properties> = ({
...
-                                        remove(index);
-                                    }}
-                                >
-                                    <Icon
-                                        name={IconName.CLOSE}
-                                        size={20}
-                                        color={Color.ERROR}
-                                    />
-                                </Pressable>
+                                {index !== 0 && (
```
Comment (mskmee) [inline mobile/src/bundles/talent/components/skills-and-projects-form/skills-and-projects-form.tsx:143]: same here !index &&

File: mobile/src/bundles/talent/store/slice.ts [hunk 21]
```diff
@@ -2,94 +2,65 @@ import { createSlice, isAnyOf } from '@reduxjs/toolkit';
...
+    updateOnboardingData,
 } from './actions';
 
 type State = {
     dataStatus: ValueOf<typeof DataStatus>;
-    profileStepData: ProfileStepDto | null;
-    badgesStepData: BadgeStepDto | null;
-    skillsStepData: SkillsStepDto | null;
+    onboardingData: UserDetailsGeneralResponseDto | null;
+    completedStep: string | null;
```
Comment (mskmee) [inline mobile/src/bundles/talent/store/slice.ts]: completedStep: ValueOf<typeof TalentOnboardingScreenName> | null;

Comment (anogire) [reply mobile/src/bundles/talent/store/slice.ts]: it is already included in onboardingData

File: mobile/src/bundles/common/enums/navigation/talent-onboarding-screen-number.enum.ts [hunk 22]
```diff
@@ -13,4 +14,15 @@ const TalentOnboardingScreenNumber: Record<
     [TalentOnboardingScreenName.PREVIEW]: 5,
 } as const;
 
-export { TalentOnboardingScreenNumber };
+const TalentOnboardingScreenNumberByStep: Record<
+    ValueOf<typeof CompletedTalentOnboardingStep>,
+    number
+> = {
+    [CompletedTalentOnboardingStep.Profile]: 1,
+    [CompletedTalentOnboardingStep['BSA Badges']]: 2,
```
Comment (katerynakostikova) [inline mobile/src/bundles/common/enums/navigation/talent-onboarding-screen-number.enum.ts]:
```suggestion
    [CompletedTalentOnboardingStep[TalentOnboardingScreenName.BSA_BADGES]]: 2,
```

File: mobile/src/bundles/common/hooks/use-onboarding-form-submit/use-onboarding-form-submit.hook.ts [hunk 23]
```diff
@@ -0,0 +1,104 @@
...
+        >();
+
+    return useCallback(
+        async (payload: OnboardingFormData): Promise<void> => {
+            const updatePayload = {
+                ...payload,
+                userId,
+                projectLinks: urlObjectsToStrings(
+                    (payload as SkillsStepDto).projectLinks,
+                ),
```
Comment (katerynakostikova) [inline mobile/src/bundles/common/hooks/use-onboarding-form-submit/use-onboarding-form-submit.hook.ts:67]: how it works if this is a step without projectLinks

**Review by nikita-remeslov — APPROVED** [review]

File: mobile/src/bundles/talent/components/badges-form/badges-form.tsx [hunk 24]
```diff
@@ -0,0 +1,74 @@
...
+    const { control, errors, handleSubmit } = useAppForm({
+        defaultValues: badgesStepData ?? BADGES_STEP_DEFAULT_VALUES,
+        validationSchema: BsaBadgesStepValidationSchema,
+    });
+
+    const handleFormSubmit = useCallback((): void => {
+        void handleSubmit(onSubmit)();
+    }, [handleSubmit, onSubmit]);
+
+    const options = Object.values(BsaBadgeStepBadgesTitle);
```
Comment (katerynakostikova) [inline mobile/src/bundles/talent/components/badges-form/badges-form.tsx]: can be moved out of component

**Review by katerynakostikova — APPROVED** [review]

File: mobile/src/bundles/common/hooks/use-onboarding-form-submit/use-onboarding-form-submit.hook.ts (hunk 23 above)
Comment (anogire) [reply mobile/src/bundles/common/hooks/use-onboarding-form-submit/use-onboarding-form-submit.hook.ts:67]: will be empty, and action accepts all fields in any case

**Review by katerynakostikova — APPROVED** [review]
