### PR TITLE
bt-286: Fix mobile navigation after sign in/up

### LINKED ISSUE #286: Fix mobile navigation after sign in/up

### PR DESCRIPTION
**Pull request by anogire**

### CODE REVIEW

File: mobile/src/navigations/root/root.tsx [hunk 1]
```diff
@@ -25,36 +25,40 @@ const Root: React.FC = () => {
...
-                <RootStack.Screen
-                    name={RootScreenName.ONBOARDING_ROOT_ROUTE}
-                    // TODO: create EmployerOnboardingNavigator for role == 'employer'
-                    component={TalentOnboardingNavigator}
-                />
-            );
-        }
-
-        return (
+    const screens = {
```
Comment (katerynakostikova) [inline mobile/src/navigations/root/root.tsx]:
```suggestion
    const  navigators = {
```

File: mobile/src/navigations/root/root.tsx [hunk 2]
```diff
@@ -25,36 +25,40 @@ const Root: React.FC = () => {
...
+        defaultScreen: (
```
Comment (katerynakostikova) [inline mobile/src/navigations/root/root.tsx]:
```suggestion
        auth: (
```

File: mobile/src/navigations/root/root.tsx [hunk 3]
```diff
@@ -25,36 +25,40 @@ const Root: React.FC = () => {
...
+        ),
+        mainScreen: (
+            <RootStack.Screen
+                name={RootScreenName.MAIN_ROOT_ROUTE}
+                component={
+                    role === UserRole.TALENT
+                        ? TalentBottomTabNavigator
+                        : EmployerBottomTabNavigator
+                }
+            />
```
Comment (katerynakostikova) [inline mobile/src/navigations/root/root.tsx]:
```suggestion
        onboarding: (
            <RootStack.Screen
                name={RootScreenName.ONBOARDING_ROOT_ROUTE}
                // TODO: create EmployerOnboardingNavigator for role == 'employer'
                component={TalentOnboardingNavigator}
            />
        ),
        main: (
            <RootStack.Screen
                name={RootScreenName.MAIN_ROOT_ROUTE}
                component={
                    role === UserRole.TALENT
                        ? TalentBottomTabNavigator
                        : EmployerBottomTabNavigator
                }
            />
```

**Review by katerynakostikova — APPROVED** [review]

**Review by mskmee — APPROVED** [review]
