### PR TITLE
bt-486: [BUG] Badge's layout isn't displayed according to design on the Scores & Skills tab

### LINKED ISSUE #486: [BUG] Badge's layout isn't displayed according to design on the Scores & Skills tab
**Description:**
The badge's layout isn't displayed according to design on the Scores & Skills tab when the resolution is 2340x1080

**Preconditions:**
The BSA talent app is open

**Environment:**
Android 13
Samsung Galaxy A52 (2340x1080)

**Steps to reproduce:**
1. Sign up
2. Go to step 05
3. Pay attention to the badge's layout

**Actual Result:**
1. Scores go out of badges
2. The word "Punctuality" breaks

**Expected Result:**
All badges are displayed according to the design
Scores don't go out of badge's blocks
Words don't break

**Visual Proof (screenshots, videos, text):**
image

**Severity:**
Major (S3)

### PR DESCRIPTION
**Pull request by illia-dobro**
looks

### CODE REVIEW

File: mobile/src/bundles/common/components/badge/styles.ts [hunk 1]
```diff
@@ -34,7 +34,7 @@ const styles = StyleSheet.create({
         backgroundColor: '#FF951A',
     },
     small: {
-        width: '48%',
+        width: '48.6%',
```
Comment (katerynakostikova) [inline mobile/src/bundles/common/components/badge/styles.ts]: this is not good way to fix this issue

File: mobile/src/bundles/common/components/badge/badge.tsx [hunk 2]
```diff
@@ -97,14 +97,35 @@ const Badge: React.FC<Properties> = ({
             </View>
             <View style={styles.textWrapper}>
                 <View style={globalStyles.flexDirectionRow}>
-                    <Text category={TextCategory.H4}>
+                    <Text
+                        category={
+                            size === BadgeSize.SMALL
+                                ? TextCategory.H5
+                                : TextCategory.H4
```
Comment (katerynakostikova) [inline mobile/src/bundles/common/components/badge/badge.tsx]: repeating of code, move to some const

**Review by katerynakostikova — CHANGES_REQUESTED** [review]

**Review by mskmee — APPROVED** [review]

**Review by katerynakostikova — APPROVED** [review]
