### PR TITLE
bt-570: Placeholder of the description field is cut off

### LINKED ISSUE #472: Change min symbols for Step1 description field
- [x] Rename "Briefly tell employers about your experience" field to "Introduce yourself"
- [x] Change the placeholder to "Candidates who share more about their experience have higher chances of getting a job offer." (only if it'll be shown well on mobile view)
- [ ] Change the min length validation to 100 symbols.
- [ ] Change the validation message according to the new rule.

Image

### LINKED ISSUE #570: [BUG] Placeholder of the "Introduce yourself" is cut off on step 01
**Description:**
Placeholder of the "Introduce yourself" is cut off on step 01 

**Preconditions:**
The BSA app is open

**Environment:**
Android 13
Samsung Galaxy A52 (2340x1080)

**Steps to reproduce:**
1. Sign up with valid credentials
2. Pay attention to the placeholder of "Introduce yourself"

**Actual Result:**
Placeholder of the "Introduce yourself" is cut off on step 01 

**Expected Result:**
Placeholder of the "Introduce yourself" is fully visible on step 01 

**Visual Proof (screenshots, videos, text):**
Screenshot_3

**Severity:**
Minor (S4)

### PR DESCRIPTION
**Pull request by likeri29**

### CODE REVIEW

**Review by anogire — APPROVED** [review]

**Review by katerynakostikova — APPROVED** [review]

File: mobile/src/bundles/common/components/input/input.tsx [hunk 1]
```diff
@@ -85,6 +85,7 @@ const Input = <T extends FieldValues>({
                 value={value}
                 onBlur={onBlur}
                 placeholderTextColor={Color.TEXT2}
+                multiline={multiline}
```
Comment (nikita-remeslov) [inline mobile/src/bundles/common/components/input/input.tsx:88]: should be with prefix! `has` or `is`

**Review by nikita-remeslov — CHANGES_REQUESTED** [review]

File: mobile/src/bundles/common/components/input/input.tsx (hunk 1 above)
Comment (katerynakostikova) [reply mobile/src/bundles/common/components/input/input.tsx:88]: it's native props
