### PR TITLE
bt-782: [BUG ] Employer Name not showing + chat page improvements

### LINKED ISSUE #782: [BUG] Chats - Employer Full Name not showing

### PR DESCRIPTION
**Pull request by JosuerBague**
Closes #782 

- Fixed logic for showing employer name correctly.
- Removed overflowing time since chat for screens 900 > 1200 (tablet)
- Add placeholder for employers with empty chats.

image

### CODE REVIEW

File: frontend/src/bundles/chat/components/chat-header/chat-header.tsx [hunk 1]
```diff
@@ -11,25 +11,20 @@ import { getValidClassNames } from '~/bundles/common/helpers/helpers.js';
 import { useAppSelector } from '~/bundles/common/hooks/hooks.js';
 import { type ApplicationRoute } from '~/bundles/common/types/application-route.type.js';
 
+import { getChatHeaderProps as getChatHeaderProperties } from '../../helpers/get-chat-header-props.js';
```
Comment (JemiJe) [inline frontend/src/bundles/chat/components/chat-header/chat-header.tsx]:
```suggestion
import { getChatHeaderProps as getChatHeaderProperties } from '~/bundles/chat/helpers/get-chat-header-props.js';
```

**Review by JemiJe — CHANGES_REQUESTED** [review]

**Review by nikita-remeslov — APPROVED** [review]
