### PR TITLE
bt-319: * Fix styles and placeholder

### LINKED ISSUE #319: [BUG] Profile onboard step does not correspond to figma design
**Description:**
Textarea font and placeholder is not the same as in the design. 
Also expected salary should not have a placeholder

### LINKED ISSUE #386: [BUG] Fix input placeholder color
**Description:**
The color of the text input doesn't match the design and other placeholder's color.

**Environment:**
Android 12, Realme 8

**Steps to reproduce:**
1. Compare the placeholder's input color with the design

**Actual Result:**
Colors of placeholders should be the same in all inputs

**Expected Result:**
The color of text input's placeholder is different. Text input has a little bit lighter color.

**Visual Proof (screenshots, videos, text):**
Image

**Severity:**
Trivial

### PR DESCRIPTION
**Pull request by ptarho**
Fixed placeholder font family, color, placeholder text and input badge part (check screenshot). 
Also fixed salaryExpectation default value to undefined to have only placeholder at the beginning
Screenshot_1

### CODE REVIEW

File: frontend/src/bundles/talent-onboarding/components/profile-step/profile-step.tsx [hunk 1]
```diff
@@ -214,6 +214,7 @@ const ProfileStep: React.FC = () => {
                     errors={errors}
                     name={'salaryExpectation'}
                     adornmentText="$"
+                    value={undefined}
```
Comment (MaksymGavatuk) [inline frontend/src/bundles/talent-onboarding/components/profile-step/profile-step.tsx:217]: Why we need to add this line ? If value={undefined} just remove it from props ?

**Review by MaksymGavatuk — CHANGES_REQUESTED** [review]

File: frontend/src/bundles/talent-onboarding/components/profile-step/profile-step.tsx (hunk 1 above)
Comment (ptarho) [reply frontend/src/bundles/talent-onboarding/components/profile-step/profile-step.tsx:217]: We need it to remove '0'  as a predefined value for this input. Right now default value type is defined as number and we can`t set default value = empty string for salaryExpectation (or otherwise we would need to change dto type, joi schema and so on). By setting value={undefined} there won`t be any React errors with controlled/uncontrolled component, we will have empty input field with our required placeholder and form validation is still works as expected.

Comment (nikita-remeslov) [reply frontend/src/bundles/talent-onboarding/components/profile-step/profile-step.tsx:217]: How we can apply some value if you hardcode it?

File: frontend/src/bundles/talent-onboarding/components/profile-step/profile-step.tsx [hunk 2]
```diff
@@ -287,7 +288,7 @@ const ProfileStep: React.FC = () => {
                     </Typography>
                 </FormLabel>
                 <Textarea
-                    placeholder="Tell us a little bit about yourself"
```
Comment (nikita-remeslov) [inline frontend/src/bundles/talent-onboarding/components/profile-step/profile-step.tsx]: back this change

**Review by nikita-remeslov — CHANGES_REQUESTED** [review]

File: frontend/src/bundles/talent-onboarding/components/profile-step/profile-step.tsx (hunk 1 above)
Comment (ptarho) [reply frontend/src/bundles/talent-onboarding/components/profile-step/profile-step.tsx:217]: @nikita-remeslov  We already merged the same approach in mobile version. This input value undefined only on first render, but onChange it will be changed and correctly saved in redux/validated via react hook form
Screenshot_2

Comment (ptarho) [reply frontend/src/bundles/talent-onboarding/components/profile-step/profile-step.tsx:217]: Screenshot_1

File: frontend/src/bundles/talent-onboarding/components/profile-step/profile-step.tsx (hunk 2 above)
Comment (ptarho) [reply frontend/src/bundles/talent-onboarding/components/profile-step/profile-step.tsx]: Done

**Review by nikita-remeslov — APPROVED** [review]

**Review by anton-otroshchenko — APPROVED** [review]
