### PR TITLE
bt-329: The layout of the Step 01 page does not match the approved design

### LINKED ISSUE #329: [BUG] The layout of the Step 01 page does not match the approved design
**Description:**
The layout of the Step 01 page does not match the approved design

**Preconditions:**
The BSA talent app is open

**Environment:**
Android 13
Samsung Galaxy A52 (2340x1080)

**Steps to reproduce:**
1. Enter valid email and password
2. Click on Sign up
3. Pay attention to the Step 01 layout

**Actual Result:**
1. Fields have different colors of placeholders
2. Salary expectations, job title, current location fields are not highlighted in red where empty
3. Salary expectations field is not required 
4. Wrong name and slider of Experience field. Experience slider shows "Beginner"
5. Salary expectations field has a default "0" number

**Expected Result:**
1. Placeholder for all fields matches the design
2. Salary expectations, job title, current location fields are highlighted in red where empty
3. Salary expectations field is displayed validation message and  highlighted in red where empty
3. Experience slider has the name "Experience" and shows years of experience (1, 1.5, 2.....).
4. Salary expectations field has a placeholder like on the design

**Visual Proof (screenshots, videos, text):**
step 01
step 1
step_01

**Severity:**
Major (S3)

### LINKED ISSUE #384: [BUG] The chosen country does not display in the field "Current location"
**Description:**
[Mobile]: The chosen country does not display in the field "Current location"

**Preconditions:**

**Environment:**
OS - Android 12
App build 13/09/2023 3:40PM

**Steps to reproduce:**

1. Open the app
2. Sign Up with valid data, press “Sign Up”
3. Fill in the required fields on the page “Step 01/05”
4. Choose country in the field "Current location"
5. Pay attention that chosen country does not display in the field "Current location"
6. Press button “Next”
7. Pay attention that validation error about empty field "Current location" does not appears, user is redirected to the next step

**Actual Result:**
The chosen country does not displayed in the field "Current location". The validation error about empty field "Current location" does not appears, user is redirected to the next step

**Expected Result:**
The chosen country displayed in the field "Current location"

**Visual Proof (screenshots, videos, text):**
https://user-images.githubusercontent.com/8355821/267261072-466b16ad-d80f-4e20-9b8a-5cb2b026ccbb.mp4
https://drive.google.com/file/d/11rvz9DF9wX5Y-QuWzNB2VN3I-yXTlWtd/view?usp=drivesdk

**Severity:**
Medium

### PR DESCRIPTION
**Pull request by anogire**
Screenshot 2023-09-11 at 15 26 58Screenshot 2023-09-11 at 15 27 04
Screenshot 2023-09-11 at 15 27 13Screenshot 2023-09-11 at 15 27 20

### CODE REVIEW

File: mobile/src/bundles/talent/components/profile-form/profile-form.tsx [hunk 1]
```diff
@@ -97,6 +97,7 @@ const ProfileForm: React.FC<Properties> = ({ profileStepData, onSubmit }) => {
                     placeholder="0000"
                     keyboardType="numeric"
                     marker="$"
+                    value={undefined}
```
Comment (katerynakostikova) [inline mobile/src/bundles/talent/components/profile-form/profile-form.tsx]: maybe initial value should be undefined?

Comment (anogire) [reply mobile/src/bundles/talent/components/profile-form/profile-form.tsx]: This will happen in the next branch, when in ProfileStepDto this field will change to the "number | undefined" type.

File: mobile/src/bundles/common/components/autocomplete-selectors/autocomplete-selector.tsx [hunk 2]
```diff
@@ -39,12 +47,13 @@ const AutocompleteSelector = <T extends FieldValues>({
     placeholder,
 }: Properties<T>): JSX.Element => {
     const { field } = useFormController({ name, control });
-    const { onBlur, onChange } = field;
+    const { value, onBlur, onChange } = field;
     const [search, setSearch] = useState('');
     const { isVisible, toggleVisibility } = useVisibility(false);
```
Comment (anogire) [inline mobile/src/bundles/common/components/autocomplete-selectors/autocomplete-selector.tsx:51]: I needed to return the value from the field and return the arrow icon, otherwise this field on the form is counted incorrectly and does not match the design.

**Comment by anogire** [comment]
After all changes

Screenshot 2023-09-11 at 18 49 09Screenshot 2023-09-11 at 18 49 15
Screenshot 2023-09-11 at 18 49 41Screenshot 2023-09-11 at 18 49 54

File: mobile/src/bundles/common/components/autocomplete-selectors/autocomplete-selector.tsx [hunk 3]
```diff
@@ -39,12 +47,13 @@ const AutocompleteSelector = <T extends FieldValues>({
     placeholder,
 }: Properties<T>): JSX.Element => {
     const { field } = useFormController({ name, control });
-    const { onBlur, onChange } = field;
+    const { value, onBlur, onChange } = field;
     const [search, setSearch] = useState('');
```
Comment (likeri29) [inline mobile/src/bundles/common/components/autocomplete-selectors/autocomplete-selector.tsx]: I guess, if you added value from controller we can omit useState.

**Review by likeri29 — APPROVED** [review]

**Comment by katerynakostikova** [comment]
Seems like 2 spaces here in error message
image

**Review by katerynakostikova — APPROVED** [review]
