### PR TITLE
bt-428: Refactor drawer logic

### LINKED ISSUE #428: [BUG] Progress bar is not displayed in blue color when step is completed
**Description:**
Progress bar is not displayed in blue color when the step is completed

**Preconditions:**
The BSA talent app is open

**Environment:**
Android 13
Samsung Galaxy A52 (2340x1080)

**Steps to reproduce:**
1. Enter a valid email and password
2. Click on Sign up
3. Fill in steps
3. Pay attention to the progress bar

**Actual Result:**
Progress line has 2 states: disabled and active
Progress bar is not displayed in blue color when step is completed

**Expected Result:**
Progress line has 3 states: disabled (grey), active(white), and completed(blue)

**Visual Proof (screenshots, videos, text):**
https://drive.google.com/file/d/1f4bxgl6l1_Xgeb3aobrj5PAJ55VNdCoL/view?usp=drive_link

**Severity:**
Major (S3)

### PR DESCRIPTION
**Pull request by mskmee**
image
image
image

### CODE REVIEW

File: mobile/src/navigations/onboarding-navigator/components/steps/steps.tsx [hunk 1]
```diff
@@ -43,14 +47,35 @@ const {
 
 const Steps: React.FC<DrawerContentComponentProps> = (props) => {
     const { navigation, state } = props;
+    const { completedStep } =
+        useAppSelector(({ talents }) => talents.onboardingData) ?? {};
+
     const progress = useDrawerProgress();
     const dispatch = useAppDispatch();
+    const stepToActiveScreen = 1;
```
Comment (katerynakostikova) [inline mobile/src/navigations/onboarding-navigator/components/steps/steps.tsx]: CAPS

Comment (katerynakostikova) [reply mobile/src/navigations/onboarding-navigator/components/steps/steps.tsx]: and move out of component

**Review by katerynakostikova — APPROVED** [review]

**Review by illia-dobro — APPROVED** [review]
