### PR TITLE
bt-387: The layout of the Step 03 page does not match the approved design

### LINKED ISSUE #387: [BUG] The layout of the Step 03 page does not match the approved design
**Description:**
The layout of the Step 03 page does not match the approved design

**Preconditions:**
The BSA talent app is open

**Environment:**
Android 13
Samsung Galaxy A52 (2340x1080)

**Steps to reproduce:**
1. Enter a valid email and password
2. Click on Sign up
3. Go to step 03
4. Pay attention to the Step 03 layout

**Actual Result:**
1.  "Level of English" and "Preferred language of communication" fields don't have the placeholder
2. "Level of English" and "Preferred language of communication" fields are not highlighted in red color when empty
3.  The First "Project links" field can be deleted and have the "delete" button
4. The First "Project links" field has the wrong placeholder
5. It's possible to add more than 5 Project links. User see validation message but still can add more than 5 links
6.  "Project links" field doesn't have a validation
7. Hard Skills field still  is highlighted in red color and has a validation message, after adding skills
8. When the user clicks on the "Next" button he isn't redirected to the next onboarding step

**Expected Result:**
1. "Level of English" and "Preferred language of communication" fields have the placeholder "Option"
2. "Level of English" and "Preferred language of communication" fields are highlighted in red color when empty
3. The First "Project links" field should be static without the possibility of deletion (without the delete button) because the BSA project link will be automatically filled from the BSA LMS
4. The First "Project links" field should have a "link to BSA project" placeholder
5.  User can't add more than 5 additional links
6. "Project links" field should have validation that it's a URL
7. Validation disappears after adding hard skills
8. When the user clicks on the "Next" button he is redirected to the next onboarding step
9.  Other additional links should have a placeholder "link to your project" and have the possibility of being deleted

**Visual Proof (screenshots, videos, text):**
https://prnt.sc/thGdzDqAZ19Y
https://prnt.sc/GPYpT61J6c8a
https://prnt.sc/qs23W7t17Hi-
https://prnt.sc/OetySxhBlFg6
https://prnt.sc/13wkxvme_yFS
https://drive.google.com/file/d/123qmj_1pq9v39Z3YMcOFyg6g1klGVsI1/view?usp=drivesdk
**Severity:**
Major (S3)

### PR DESCRIPTION
**Pull request by likeri29**

### CODE REVIEW

File: mobile/src/bundles/common/components/form-field/form-field.tsx [hunk 1]
```diff
@@ -43,11 +43,17 @@ const FormField = <T extends FieldValues>({
...
+                if (!child) {
+                    return;
+                }
+                return React.cloneElement(
+                    child as React.ReactElement<Properties<T>>,
+                    {
+                        hasError,
+                    },
+                );
+            })}
```
Comment (likeri29) [inline mobile/src/bundles/common/components/form-field/form-field.tsx:56]: had to change this to show error for each project link. Nothing is broken

**Review by nikita-remeslov — COMMENTED** [review]
Conflicts

**Review by katerynakostikova — APPROVED** [review]

**Review by illia-dobro — APPROVED** [review]
