### PR TITLE
bt-458: [BUG] CV field accepts restricted file formats

### LINKED ISSUE #458: [BUG] CV field accepts restricted file formats
**Description:**
CV field not validating file format correctly

**Environment:**
Win 11, Chrome 116

**Steps to reproduce:**
1. Go to Step 4
2. Upload 

**Actual Result:**
User can upload URL, HTML file as CV

**Expected Result:**
Only pdf, doc, docx formats are accepted

**Visual Proof (screenshots, videos, text):**
Image

**Severity:**
Major

### PR DESCRIPTION
**Pull request by nika-sirak**
Screenshot 2023-09-17 at 15 38 41

### CODE REVIEW

File: frontend/src/bundles/talent-onboarding/components/contacts-cv-step/contacts-cv-step.tsx [hunk 1]
```diff
@@ -339,7 +345,9 @@ const ContactsCVStep: React.FC = () => {
                     />
 
                     <FormHelperText className={styles.fileError}>
-                        {errors.cv?.type === 'fileSize' && errors.cv.message}
+                        {errors.cv?.type === 'fileSize' ||
+                            (errors.cv?.type === 'fileType' &&
+                                errors.cv.message)}
```
Comment (ptarho) [inline frontend/src/bundles/talent-onboarding/components/contacts-cv-step/contacts-cv-step.tsx]: There is a typo with brackets, I don`t see an error when trying to upload file greater than 5mb
{(errors.cv?.type === 'fileSize' || errors.cv?.type === 'fileType') && errors.cv.message}

**Review by ptarho — CHANGES_REQUESTED** [review]

File: frontend/src/bundles/talent-onboarding/components/contacts-cv-step/contacts-cv-step.tsx (hunk 1 above)
Comment (nika-sirak) [reply frontend/src/bundles/talent-onboarding/components/contacts-cv-step/contacts-cv-step.tsx]: fixed

**Review by nikita-remeslov — APPROVED** [review]

**Review by ptarho — APPROVED** [review]
