### PR TITLE
bt-365: [BUG] Selector list should appear above screen content

### LINKED ISSUE #365: [BUG] Selector list should appear above screen content
Description:
When user click on selector component, screen content under it moved with the list

Environment:
OS - Android

Steps to reproduce:

1. Open the app
2. Go to onboarding step 3
3. Tap on selector component

Actual Result:
Selector list moved all screen content under it 

Expected Result:
Selector list should appear above screen content

https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/103518438/77ea2f06-9127-4151-bac9-fc25edb451cb

### PR DESCRIPTION
**Pull request by illia-dobro**
https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/112649713/2d90892a-7202-410f-9eb8-6cd70e3b8ad1

### CODE REVIEW

File: mobile/src/bundles/common/components/selector/selector.tsx [hunk 1]
```diff
@@ -123,7 +123,7 @@ const Selector = <T extends FieldValues>({
                     globalStyles.pl20,
                     globalStyles.width100,
                     isVisible && globalStyles.pb5,
-                    styles.dropdownButton,
```
Comment (katerynakostikova) [inline mobile/src/bundles/common/components/selector/selector.tsx:130]: Does styles.dropdownButton is used anywhere else? If not we should remove it

Comment (illia-dobro) [reply mobile/src/bundles/common/components/selector/selector.tsx:130]: We use it, gives border to button

**Review by nikita-remeslov — COMMENTED** [review]
Condlicts

**Review by katerynakostikova — APPROVED** [review]

**Review by anogire — APPROVED** [review]
