### PR TITLE
bt-688: Profile name instead of Full name

### LINKED ISSUE #688: [BUG] Full name field displays the profile name on the onboarding flow
**Description:**
Full name field displays the profile name on the onboarding flow when filling in steps 1-4 and go to step 4

**Preconditions:**
The BSA talent app is open

**Environment:**
Android 13
Samsung Galaxy A52 (2340x1080)

**Steps to reproduce:**
1. Sign up as a talent
2. Fill out steps 1-3
3. Go to step 4
4. Pay attention to the Full name field

**Actual Result:**
When a user fills in steps 1-3 and goes to step 4 the Full name field displays the already profile name (which was entered in step 1)

**Expected Result:**
When a user fills in steps 1-3 and goes to step 4 the Full name field displays a user name (should be pulled from LMS) 

**Visual Proof (screenshots, videos, text):**
Screenshot_16
Screenshot_17

**Severity:**
Major (S3)

### LINKED ISSUE #743: Add placeholder “There are no active conversations yet When employers want to contact you, all chats will be here” on the page "Chat" before receiving the first message from an employer
You can see screen https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/742

### PR DESCRIPTION
**Pull request by anogire**

### CODE REVIEW

File: mobile/src/bundles/chat/components/search/search.tsx [hunk 1]
```diff
@@ -24,7 +24,7 @@ const Search: React.FC<Properties> = ({
             value={searchQuery}
             placeholder="Search messages"
             placeholderTextColor={Color.TEXT2}
-            style={[globalStyles.pl15, containerStyle]}
+            style={[globalStyles.pl15, globalStyles.Input, containerStyle]}
```
Comment (katerynakostikova) [inline mobile/src/bundles/chat/components/search/search.tsx:27]:
```suggestion
            style={[globalStyles.pl15, globalStyles.input, containerStyle]}
```

**Review by katerynakostikova — APPROVED** [review]

**Review by likeri29 — APPROVED** [review]
