### PR TITLE
bt-350: [BUG] Step 3 doesn't correspond the design

### LINKED ISSUE #350: [BUG] Step 3 doesn't correspond the design
**Description:**
The layout of the Step 3 page does not correspond to the approved design

**Environment:**
Win 11, Chrome 116

**Steps to reproduce:**

1. Sign in to the app as a Talent
2. Go to Step 3
3. Fill in all fields with valid data as on the screenshot

**Actual Result:**
The layout does not correspond to the approved design

**Expected Result:**
1. Level of English field should have the same paddings on top and bottom.
2. I do not consider field should have less space between checkboxes
3. Preferred language field hint should be "Preferred language is required"(not languageS)
4.  Project links should have value validation according to the doc(5-50 symbols, A-Z, a-z, 0-9, special chars). For now value "www.site.ua" triggers an error.
5. "Add more links" should have a smaller top margin as on the design.
6. "Add more links" should have a delete field function to remove unnecessary fields.

**Visual Proof (screenshots, videos, text):**
Image

**Severity:**
Minor

### LINKED ISSUE #457: [BUG] Project link field bugs
**Description:**
Error messages appear on the empty Project link field when going to the next step

**Environment:**
Win 11, Chrome 116

**Steps to reproduce:**
1. Go to Step 3
2. Fill in all fields
3. Add two Project links and fill only one of them, leave the other empty
4. Go to the next step

**Actual Result:**
1. Error message appears for each empty Project link field
2. Project link has no delete button
3. Project links haven't updated if user saved one and then went back and delete it

**Expected Result:**
1. No errors when leaving the Priojct link empty
2. Project link should have a delete field function to remove unnecessary fields.
3. Project links should always updates when go to the Next Step

**Visual Proof (screenshots, videos, text):**
Image
Image

**Severity:**
Medium

### PR DESCRIPTION
**Pull request by MChornomaz**
closes #350 
#457 

Level of English field should have the same paddings on top and bottom.
I do not consider field should have less space between checkboxes
Preferred language field hint should be "Preferred language is required"(not languageS)
Project links should have value validation according to the doc(5-50 symbols, A-Z, a-z, 0-9, special chars). For now value "www.site.ua" triggers an error.
"Add more links" should have a smaller top margin as on the design.
"Add more links" should have a delete field function to remove unnecessary fields.
Visual Proof (screenshots, videos, text):
image

### CODE REVIEW

File: frontend/src/bundles/talent-onboarding/components/skills-step/components/close-icon/close-icon-button.tsx [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+import { useCallback } from '~/bundles/common/hooks/hooks.js';
+
+import styles from './styles.module.scss';
+
+type Properties = {
+    index: number;
+    onClick: (index: number) => void;
+};
+const CloseIconButton: React.FC<Properties> = ({ index, onClick }) => {
+    const clickHandler = useCallback(() => {
```
Comment (nikita-remeslov) [inline frontend/src/bundles/talent-onboarding/components/skills-step/components/close-icon/close-icon-button.tsx]: A10 - https://github.com/BinaryStudioAcademy/quality-criteria/blob/production/src/javascript.md

**Review by nikita-remeslov — CHANGES_REQUESTED** [review]

File: frontend/src/bundles/common/components/select/styles.module.scss [hunk 2]
```diff
@@ -22,9 +22,14 @@
 }
 
 .placeholder {
+    padding: 0;
     color: var(--nepal);
 }
 
+.container .input > div {
```
Comment (ptarho) [inline frontend/src/bundles/common/components/select/styles.module.scss]: We can`t use global tags
B10
https://github.com/BinaryStudioAcademy/quality-criteria/blob/production/src/javascript.md

File: frontend/src/bundles/talent-onboarding/components/skills-step/components/skills-project-links.tsx [hunk 3]
```diff
@@ -66,6 +74,12 @@ const SkillsProjectLinks: React.FC<Properties> = ({ control, name }) => {
                             name={fieldPath}
                             {...withoutReferenceAndName}
                         />
+                        {index !== 0 && (
+                            <CloseIconButton
+                                index={index}
+                                onClick={removeLink}
+                            />
+                        )}
```
Comment (ptarho) [inline frontend/src/bundles/talent-onboarding/components/skills-step/components/skills-project-links.tsx:62]: When link is long closeIcon is overlap with it. Also if there is an error this Icon also move from it`s place
Screenshot_4
I am not sure about it, but even link without www/http/https is treated as valid (link.com). I think we need to clarify it with qa team

File: frontend/src/bundles/talent-onboarding/components/skills-step/styles.module.scss [hunk 4]
```diff
@@ -91,14 +91,19 @@
     .MuiGrid-item {
         padding-top: 0;
     }
+
+    .MuiGrid-item > label > span {
+        padding: 6px;
+    }
```
Comment (ptarho) [inline frontend/src/bundles/talent-onboarding/components/skills-step/styles.module.scss]: B10
https://github.com/BinaryStudioAcademy/quality-criteria/blob/production/src/javascript.md

File: frontend/src/bundles/talent-onboarding/components/skills-step/components/close-icon/close-icon-button.tsx [hunk 5]
```diff
@@ -0,0 +1,25 @@
...
+    onClick: (index: number) => void;
+};
+const CloseIconButton: React.FC<Properties> = ({ index, onClick }) => {
+    const handleClick = useCallback(() => {
+        onClick(index);
+    }, [index, onClick]);
+
+    return (
+        <Close
+            color="error"
```
Comment (ptarho) [inline frontend/src/bundles/talent-onboarding/components/skills-step/components/close-icon/close-icon-button.tsx]: This color is not the same we already use for errors text in our forms:
Color of icon: #d32f2f;
Color of error text:  #ff2121

**Review by vladjsp — COMMENTED** [review]
Not about this ticket but still. Select option placeholder has 14px fonst-size when according to Figma it is 13px.
Also checkboxes are shifted 
fixfix

File: frontend/src/bundles/talent-onboarding/components/skills-step/components/skills-project-links.tsx (hunk 3 above)
Comment (nikita-remeslov) [reply frontend/src/bundles/talent-onboarding/components/skills-step/components/skills-project-links.tsx:62]: @MChornomaz what about this comment?

**Review by nikita-remeslov — CHANGES_REQUESTED** [review]

File: frontend/src/bundles/talent-onboarding/components/skills-step/components/skills-project-links.tsx (hunk 3 above)
Comment (MChornomaz) [reply frontend/src/bundles/talent-onboarding/components/skills-step/components/skills-project-links.tsx:62]: Fixed

File: frontend/src/bundles/talent-onboarding/components/skills-step/components/close-icon/close-icon-button.tsx (hunk 5 above)
Comment (MChornomaz) [reply frontend/src/bundles/talent-onboarding/components/skills-step/components/close-icon/close-icon-button.tsx]: fixed

File: frontend/src/bundles/common/components/select/styles.module.scss (hunk 2 above)
Comment (MChornomaz) [reply frontend/src/bundles/common/components/select/styles.module.scss]: fixed

**Review by vladjsp — APPROVED** [review]

File: frontend/src/bundles/talent-onboarding/components/skills-step/components/skills-project-links.tsx [hunk 6]
```diff
@@ -9,14 +9,15 @@ import { type SkillsStepDto } from '~/bundles/talent-onboarding/types/types.js';
...
+import { CloseIconButton } from './close-icon/close-icon-button.js';
 
 type Properties = {
     control: Control<SkillsStepDto>;
     errors: FieldErrors<SkillsStepDto>;
 };
 
 const SkillsProjectLinks: React.FC<Properties> = ({ control, errors }) => {
-    const { fields, append } = useFieldArray({
+    const { fields, append, remove } = useFieldArray({
```
Comment (anton-otroshchenko) [inline frontend/src/bundles/talent-onboarding/components/skills-step/components/skills-project-links.tsx:19]: Not related to this pr but I think it will be better to move this hook import to hooks.ts and import it from there

Comment (MChornomaz) [reply frontend/src/bundles/talent-onboarding/components/skills-step/components/skills-project-links.tsx:19]: Fixed this import

**Review by ptarho — APPROVED** [review]

**Review by nikita-remeslov — APPROVED** [review]
