### PR TITLE
bt-318: but the layout of the sign in page does not correspont to the approved desig

### LINKED ISSUE #318: [BUG] The layout of the Sign in page does not correspond to the approved design
**Description:**
The layout of the Sign in page does not correspond to the approved design

**Environment:**
Android 13
Samsung Galaxy A52 (2340x1080)

**Steps to reproduce:**
1. Open BSA talent app
2. Pay attention to the page layout

**Actual Result:**
1. Email and password required fields don't have "*"
2.  Not Registered Yet and Create an account are out of bounds sign in screen

**Expected Result:**
1.  Email and password required fields have "*"
2. Not Registered Yet and Create an account correspond to the approved design
**Visual Proof (screenshots, videos, text):**
Screenshot_11

Sign in mockup:
Screenshot_12

**Severity:**
Major (S3)

### PR DESCRIPTION
**Pull request by mskmee**
image
If text description would grater than background, text will wrap on the next line

### CODE REVIEW

File: mobile/src/bundles/auth/components/sign-in-form/sign-in-form.tsx [hunk 1]
```diff
@@ -51,7 +59,7 @@ const SignInForm: React.FC<Properties> = ({ onSubmit }) => {
             <View style={styles.formWrapper}>
                 <FormField
                     errorMessage={errors.email?.message}
-                    label="Email"
+                    label="Email*"
```
Comment (likeri29) [inline mobile/src/bundles/auth/components/sign-in-form/sign-in-form.tsx]: If we really need this * in the label (because in the design we don't have this) just pass to FormField `required`

File: mobile/src/bundles/auth/components/sign-in-form/sign-in-form.tsx [hunk 2]
```diff
@@ -92,11 +94,13 @@ const SignInForm: React.FC<Properties> = ({ onSubmit }) => {
...
-                    globalStyles.justifyContentCenter,
-                    globalStyles.mt20,
+                    globalStyles.justifyContentSpaceBetween,
+                    globalStyles.alignItemsCenter,
+                    globalStyles.m10,
+                    styles.signUpWrapper,
                 ]}
             >
-                <Text style={styles.text}>Not Registered Yet? </Text>
+                <Text style={[styles.text]}>Not Registered Yet?</Text>
```
Comment (katerynakostikova) [inline mobile/src/bundles/auth/components/sign-in-form/sign-in-form.tsx]:
```suggestion
                <Text style={styles.text}>Not Registered Yet?</Text>
```

File: mobile/src/bundles/auth/components/sign-in-form/styles.ts [hunk 3]
```diff
@@ -20,6 +20,11 @@ const styles = StyleSheet.create({
         color: Color.PRIMARY,
         fontFamily: FontFamily.INTER_SEMIBOLD,
     },
+    signUpWrapper: {
```
Comment (katerynakostikova) [inline mobile/src/bundles/auth/components/sign-in-form/styles.ts]:
```suggestion
    linkContainer: {
```

**Review by katerynakostikova — APPROVED** [review]

**Review by likeri29 — APPROVED** [review]
