### PR TITLE
bt-537:  Fix spaces between required asterisk

### LINKED ISSUE #537: [BUG] Sign Up page UI bugs
**Description:**
Sign up\Sign In pages have some visual bugs

**Environment:**
Win 11, Chrome 116

**Steps to reproduce:**
1. Open Sign up page
2. Select Talent's radio button

**Actual Result:**
1. Error message about unselected Terms shown visually as a backend error
2. "*" symbol divided from text with a space
3. Radiobuttons have a wrong alignment

**Expected Result:**
1. We should use the hint and red outline on BSA Terms checkbox in the same way as everywhere else in the app
2. All required fields on Sign In and Sign Up pages should have "*" symbol next to them without space (Email*)
3. Radibuttons should be aligned left with the checkbox

**Visual Proof (screenshots, videos, text):**
Image

**Severity:**
Medium

### PR DESCRIPTION
**Pull request by lavandosya**

### CODE REVIEW

**Review by nikita-remeslov — APPROVED** [review]

**Review by ptarho — APPROVED** [review]

File: frontend/src/bundles/auth/components/auth-forms/sign-in-form/sign-in-form.tsx [hunk 1]
```diff
@@ -47,7 +47,10 @@ const SignInForm: React.FC<Properties> = ({ onSubmit }) => {
                         errors.email ? '' : 'email',
                     )}
                 >
-                    <FormLabel className="label">Email*</FormLabel>
+                    <FormLabel className="label">
```
Comment (Monyster) [inline frontend/src/bundles/auth/components/auth-forms/sign-in-form/sign-in-form.tsx:50]:
```suggestion
                    <FormLabel className="label" required>
```

File: frontend/src/bundles/auth/components/auth-forms/sign-in-form/sign-in-form.tsx [hunk 2]
```diff
@@ -47,7 +47,10 @@ const SignInForm: React.FC<Properties> = ({ onSubmit }) => {
...
+                        Email
+                        <span className={styles.required}>*</span>
```
Comment (Monyster) [inline frontend/src/bundles/auth/components/auth-forms/sign-in-form/sign-in-form.tsx:52]:
```suggestion
                        
```

File: frontend/src/bundles/auth/components/auth-forms/sign-in-form/sign-in-form.tsx [hunk 3]
```diff
@@ -61,7 +64,10 @@ const SignInForm: React.FC<Properties> = ({ onSubmit }) => {
                         errors.password ? '' : 'password',
                     )}
                 >
-                    <FormLabel className="label">Password*</FormLabel>
+                    <FormLabel className="label">
```
Comment (Monyster) [inline frontend/src/bundles/auth/components/auth-forms/sign-in-form/sign-in-form.tsx:67]:
```suggestion
                    <FormLabel className="label" required>
```

File: frontend/src/bundles/auth/components/auth-forms/sign-in-form/sign-in-form.tsx [hunk 4]
```diff
@@ -61,7 +64,10 @@ const SignInForm: React.FC<Properties> = ({ onSubmit }) => {
...
+                        Password
+                        <span className={styles.required}>*</span>
```
Comment (Monyster) [inline frontend/src/bundles/auth/components/auth-forms/sign-in-form/sign-in-form.tsx:69]:
```suggestion
```

File: frontend/src/bundles/auth/components/auth-forms/sign-up-form/sign-up-form.tsx [hunk 5]
```diff
@@ -103,7 +103,8 @@ const SignUpForm: React.FC<Properties> = ({ onSubmit }) => {
                     )}
                 >
                     <FormLabel className="label">
-                        Email <span className={styles.required}>*</span>
+                        Email
+                        <span className={styles.required}>*</span>
```
Comment (Monyster) [inline frontend/src/bundles/auth/components/auth-forms/sign-up-form/sign-up-form.tsx:107]:
```suggestion
```

File: frontend/src/bundles/auth/components/auth-forms/sign-up-form/sign-up-form.tsx [hunk 6]
```diff
@@ -103,7 +103,8 @@ const SignUpForm: React.FC<Properties> = ({ onSubmit }) => {
                     )}
                 >
                     <FormLabel className="label">
```
Comment (Monyster) [inline frontend/src/bundles/auth/components/auth-forms/sign-up-form/sign-up-form.tsx:105]:
```suggestion
                    <FormLabel className="label" required>
```

File: frontend/src/bundles/auth/components/auth-forms/sign-up-form/sign-up-form.tsx [hunk 7]
```diff
@@ -119,7 +120,8 @@ const SignUpForm: React.FC<Properties> = ({ onSubmit }) => {
...
```
Comment (Monyster) [inline frontend/src/bundles/auth/components/auth-forms/sign-up-form/sign-up-form.tsx:122]:
```suggestion
                    <FormLabel className="label" required>
```

File: frontend/src/bundles/auth/components/auth-forms/sign-up-form/sign-up-form.tsx [hunk 8]
```diff
@@ -119,7 +120,8 @@ const SignUpForm: React.FC<Properties> = ({ onSubmit }) => {
...
-                        Password <span className={styles.required}>*</span>
+                        Password
+                        <span className={styles.required}>*</span>
```
Comment (Monyster) [inline frontend/src/bundles/auth/components/auth-forms/sign-up-form/sign-up-form.tsx:124]:
```suggestion
```

**Review by Monyster — CHANGES_REQUESTED** [review]
